#### GENERAL CONFIGURATION ####

# Define the directory containing the paired end FASTQ files
fastq_dir_paired_unmerged: "FASTQ/rna_paired/merged"

# Are there technical duplicates?
technical_duplicates: false

# Define the extension of the paired end samples:
sample_extension: "_mergedF"

# Define the directory containing the single end FASTQ files
fastq_dir_single_end: "FASTQ/single_end"

# Perform FASTQC? (yes or no)
run_fastqc: "yes"

# Perform multiQC? (yes or no, run_fastqc must be yes)
do_multiqc: "yes"

#### TRIMMOMATIC OPTIONS ####
## ILLUMINACLIP
seed_mismatches: 2

palindrome_clip_threshold: 30

simple_clip_threshold: 10

## SLIDINGWINDOW
window_size: 5
required_qual: 20

## LEADING
leading_qual: 3

## TRAILING
trailing_qual: 3

## MINLEN
minlen: 50

#### KALLISTO SINGLE END OPTIONS ####

fragment_length: 260

sdev: 20